In [1]:
import numpy as np
from scipy.spatial.distance import cdist

In [2]:
X_train = np.arange(24).reshape(6, 4)
X_train

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
X_test = np.array([
    [1, 1, 0, -1],
    [2, -5, 1, 3]
])

In [4]:
dists = np.zeros((len(X_test), len(X_train)))
for i in range(len(X_test)):
    dists[i] = np.sum(np.square(X_test[i] - X_train), axis=1)

In [5]:
dists

array([[   21.,   125.,   357.,   717.,  1205.,  1821.],
       [   41.,   145.,   377.,   737.,  1225.,  1841.]])

In [6]:
np.dot(X_test.T, X_test)

array([[  5,  -9,   2,   5],
       [ -9,  26,  -5, -16],
       [  2,  -5,   1,   3],
       [  5, -16,   3,  10]])

In [7]:
np.sum(np.square(X_test.reshape((2, 1, -1)) - X_train), axis=-1)

array([[  21,  125,  357,  717, 1205, 1821],
       [  41,  145,  377,  737, 1225, 1841]])

In [8]:
np.sum(np.square(X_test[:, np.newaxis, :] - X_train[np.newaxis, :, :]), axis=2)

array([[  21,  125,  357,  717, 1205, 1821],
       [  41,  145,  377,  737, 1225, 1841]])

In [9]:
cdist(X_test, X_train, 'sqeuclidean')

array([[   21.,   125.,   357.,   717.,  1205.,  1821.],
       [   41.,   145.,   377.,   737.,  1225.,  1841.]])

### Matrix multiplication
~~~python
dist(x, y) = sqrt(dot(x, x) - 2 * dot(x, y) + dot(y, y))
~~~

In [10]:
np.multiply(X_test, X_test)

array([[ 1,  1,  0,  1],
       [ 4, 25,  1,  9]])

In [11]:
np.multiply(X_train, X_train)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [12]:
XX = np.sum(X_test * X_test, axis=1)[:, np.newaxis]
YY = np.sum(X_train * X_train, axis=1)[np.newaxis, :]
print('XX:', XX)
print('YY:', YY)

XX: [[ 3]
 [39]]
YY: [[  14  126  366  734 1230 1854]]


In [13]:
distances = np.dot(X_test, X_train.T)
distances *= -2
distances += XX
distances += YY
np.maximum(distances, 0, out=distances)

array([[  21,  125,  357,  717, 1205, 1821],
       [  41,  145,  377,  737, 1225, 1841]])

In [14]:
%%timeit
dists = np.zeros((len(X_test), len(X_train)))
for i in range(len(X_test)):
    dists[i] = np.sum(np.square(X_test[i] - X_train), axis=1)

The slowest run took 9.10 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 17.1 µs per loop


In [15]:
%timeit np.sum(np.square(X_test[:, np.newaxis, :] - X_train[np.newaxis, :, :]), axis=2)
%timeit cdist(X_test, X_train, 'sqeuclidean')

The slowest run took 5.56 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 8.34 µs per loop
10000 loops, best of 3: 19.1 µs per loop


In [16]:
%%timeit
XX = np.sum(X_test * X_test, axis=1)[:, np.newaxis]
YY = np.sum(X_train * X_train, axis=1)[np.newaxis, :]
distances = np.dot(X_test, X_train.T)
distances *= -2
distances += XX
distances += YY
np.maximum(distances, 0, out=distances)

The slowest run took 4.86 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 17.8 µs per loop


## Fancy indexing

In [17]:
arr = np.arange(15).reshape((3, -1))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr[np.arange(3), [3, 4, 0]]

array([ 3,  9, 10])

In [19]:
np.choose([3, 4, 0], arr.T)

array([ 3,  9, 10])